<script>
    appConfig = <?php echo $appConfig;?>
</script>

<div id="app">

    <div class="line">
        <div id="search-box">
        </div>
    </div>

    <div class="line">
        <div id="refinement-list">
        </div>
    </div>

    <div class="line">
        <div id="pagination-container">
        </div>
        <div id="sorter">
        </div>
    </div>

    <div class="line">
        <div id="hits" v-on:click="deleteFormInit($event)">
        </div>
    </div>

    <div class="line">
        <div id="pagination-container-bottom">
        </div>
    </div>


    <div class="line form">
        <fieldset id="deleteFieldset">
            <legend>Delete a record by its Id</legend>
            <form action="/api/1/apps" id="deleteForm">
                <ul>
                    <li><input type="text" name="id" id="id-to-delete" value=""></li>
                    <li><input type="submit" value="Delete" v-on:click="deleteFormSubmit($event)"/></li>
                </ul>
                <div class="message" id="delete-message"></div>
            </form>
        </fieldset>
        <fieldset>
            <legend>Add a new record</legend>
            <form action="/api/1/apps" id="postForm">
                <ul>
                    <li><input type="text" name="name" id="name" value="test name" placeholder="name"></li>
                    <li><input type="text" name="category" id="category" value="Books" placeholder="category"></li>
                    <li><input type="text" name="link" id="link" value="http://test.link" placeholder="link"></li>
                    <li><input type="number" name="rank" id="rank" value="10" placeholder="rank"></li>
                    <li><input type="text" name="image" id="image" value="http://image.jpg" placeholder="image"></li>
                    <li><input type="submit" value="Post" v-on:click="postFormSubmit($event)"/></li>
                </ul>
                <div class="message" id="post-message"></div>
            </form>
        </fieldset>
    </div>
</div>
