<!DOCTYPE html>
<meta name="viewport" content="width=device-width"/>
<html>
<head>
    <meta charset="utf-8"/>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css" rel="stylesheet" type="text/css">
    <link href="/css/algolia-test.css" rel="stylesheet" type="text/css">
    <?php echo $styles; ?>
    <?php echo $js_head; ?>
</head>
<body>

<h1>Algolia Test modified</h1>
<?php echo $content ?>
<?php echo $js_body; ?>

</body>
</html>
